### ISSUE TITLE
: Cannot find module './config_ctrl'

### ISSUE THREAD

**Issue by xhottam** [skydive-project/skydive-grafana-datasource#1]
From skydive-grafana-datasource\src\module.js you are trying config_ctrl but the file doesn't exits.

import {SkydiveConfigCtrl} from './config_ctrl';

In below commit you were fine
bdbaa50ce3a3aede1dd26718647a965c29430fe6

Running "mochaTest:test" (mochaTest) task
>> Mocha exploded!
>> Error: Cannot find module './config_ctrl'
>>     at Function.Module._resolveFilename (module.js:469:15)
>>     at Function.Module._load (module.js:417:25)
>>     at Function.Module._load (/home/grafana/skydive-grafana-datasource/node_modules/prunk/index.js:92:22)
>>     at Module.require (module.js:497:17)
>>     at require (internal/module.js:20:19)
>>     at Object.<anonymous> (/home/grafana/skydive-grafana-datasource/dist/test/module.js:10:20)
>>     at Module._compile (module.js:570:32)
>>     at Object.Module._extensions..js (module.js:579:10)
>>     at Module.load (module.js:487:32)
>>     at tryModuleLoad (module.js:446:12)
Warning: Task "mochaTest:test" failed. Use --force to continue.

**Comment by safchain** [comment]
Hi, Yes sorry :( 

going to submit it in a sec
